### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by harex15** [BlackLight/platypush#133]
Hi there,

I'm really appreciate your work. I'm long time user of HA. However, I'm building some kind of a nursing home assistant robot. Originally, I used ROS, but then I went to HA+Node-Red+MyOwnCode. But recently, I found your article on Medium 'Build your own customizable voice assistant with platypush'. It is really seems promised. And I'm really like your demonstration of how it works. I'm trying to do that  following your instruction, but stuck in the beginning of installing the platypush.

a. 'systemctl enable redis.service' = Error: too many symbolic links
b. 'pip install platypush' = no folder '/etc/platypush/' neither '~/.config/platypush/config/'
c. Manual installation = many errors with 'python setup.py build install'

Upgraded Python from 2.7 to 3.7.
The system:
Raspberry Pi 4 (4G)
OS: Raspbian Buster

I'll really appreciate your assistance and help.

**Comment by BlackLight** [comment]
a. The Redis error seems to be installation related. It's likely that you have the `redis.service` file defined somewhere as a symbolic link, and you've got a symbolic loop in its definition.

b. No `/etc/platypush` nor `~/.config/platypush/config` folder will be created on installation. You can either create the folder yourself with the `config.yaml` file or use a different config file at startup with the `-c` option. You can refer to the examples in the article or the sample [`config.yaml`](https://github.com/BlackLight/platypush/blob/master/examples/conf/config.yaml) for syntax. However, if the pip installation didn't show any errors then the service is installed.

c. "Many errors on python setup.py build install" doesn't really help as a description.

**Comment by WojtekKozaczynski** [comment]
I am also having issues (a) and (b) on Raspberry Pi 3 with a fresh, recommended Raspbian image. 

(a) There is no Redis on Raspbian, so this is the first time it is installed. "redis.service" is a symlink in /etc/systemd/system pointing at /lib/systemd/system/redis-server.service. I cannot find any other "redis.service" symlink and "redis-server.service" looks OK to me. This issues should be easy to reproduce on a fresh Raspbian image.

(b) The error massage I got was that setup.py required python 3.x but the Raspbian's default is python 2.7. This can be corrected by repointing the "python" symlink in /usr/bin (sudo ln -sf python3 python).

**Comment by BlackLight** [comment]
1. True, Raspbian names the Redis service redis-server for some reason. Using that will work.

2. The latest Raspbian should default to Python 3, on previous installations that use Python 2 as a default you should simply start the setup with python3 setup.py build install, without changing the symlink of the system interpreter, because it could break other packages.

**Comment by WojtekKozaczynski** [comment]
Thanks Fabio. 

The following sequence of installation commands on a fresh Raspbian image worked fine:
```
cd ~
sudo apt-get install redis-server
sudo systemctl start redis-server
sudo systemctl enable redis-server
sudo git clone https://github.com/BlackLight/platypush 
cd platypush
sudo python3 setup.py build install
```

BTW, the latest version (Feb. 2020) of Raspbian still defaults to Python 2.
