### ISSUE TITLE
Provide Engine & Log Command Line Arguments

### ISSUE THREAD

**Issue by julianrichen** [BlackLight/platypush#160]
Currently you can override the `config.yaml` location via the command line:
```
../platypush -c "/path/to/config.yaml"
```

It would be nice if we could override the engine location and log location via the command line like:

```
../platypush -e /path/to/engine.db -l /path/to/log/dir/
```

Currently it can be done via the `config.yaml` but it would be nice to do it via the command line. I have Ansible script to deploy the application to my server and `config.yaml` is provided in the playbook before I calculate were the engine or log will be stored. It would be nice to let me set the default locations I expect to deploy the file and if needed I can override it in the `config.yaml` I later deploy.

**Comment by BlackLight** [comment]
I usually consider the replication of options between the configuration file and the command line a bit redundant (I like the idea of `config.yaml` being the only source of truth for the configuration), but in the specific case of logs dir, work dir and engine path I see the use case - one could deploy the same configuration file to multiple services either on the same machine or different machines that would point to different directories. I'll add this to the backlog.

**Comment by BlackLight** [comment]
See https://github.com/BlackLight/platypush/issues/159
