### ISSUE TITLE
Remove or Offline Third Party Scripts & Styles

### ISSUE THREAD

**Issue by julianrichen** [BlackLight/platypush#161]
Currently the [css-common](https://github.com/BlackLight/platypush/blob/master/platypush/backend/http/templates/css-common.html) template links to `fonts.googleapis.com` and `fontawesome.com`. To act more as an offline and private home automation hub can these scripts either be offline or removed so your private instance of platypush isn't reaching outside to the web unless it's some automation you've enabled yourself?

**Comment by BlackLight** [comment]
This has already been done on the new [`vuejs` refactor branch](https://github.com/BlackLight/platypush/tree/vuejs) - I have rewritten the entire UI with Vue 3 and true responsive design, and the build pipeline only uses local files. This branch also removes the need for compiling the SASS stylesheets from `setup.py`, therefore removing the `pyScss` dependency and considerably speeding up the installation time.

The new branch is still work in progress, as I'm rewriting the available integrations one by one, but feel free to start using it and playing with it.
