### ISSUE TITLE
Windows does not come with os.environ['HOME']

### ISSUE THREAD

**Issue by AVeryLostNomad** [BlackLight/platypush#74]
On windows, the default platypush cloned from github will fail on run, citing a missing environment key.

![powershell_2019-07-28_16-35-35](https://user-images.githubusercontent.com/19557336/62013288-d37c8380-b155-11e9-8df2-00f27b80e007.png)

My suggestion is to replace these 'os.environ['HOME']' lines in the config __init__.py with 
`os.path.expanduser('~')`, which should be platform agnostic.

**Comment by BlackLight** [comment]
Thanks for the report. I have replaced the occurrences of `os.environ['HOME']` and similar in https://github.com/BlackLight/platypush/commit/dcb4a36959ab18685ea522f89ca03074710c06e3. Unfortunately I don't have a Windows machine at hand to test it, but let me know if it works.

**Comment by AVeryLostNomad** [comment]
I believe that should have fixed it. Thanks for the quick response.
