### ISSUE TITLE
ImportError: No module named 'scss'

### ISSUE THREAD

**Issue by doumpap** [BlackLight/platypush#85]
hi, i try to install your project on my raspberry pi 3 b+ with a fresh install of raspbian Stretch.
when i enter this command  "python setup.py build"
I have this error "from scss import Compiler
ImportError: No module named 'scss'"

**Comment by BlackLight** [comment]
`scss` is required to pre-process the stylesheets used by the web panel. You can install it like this:

```
pip install pyScss
```

In general, all the required dependencies can be installed via:

```
pip install -r requirements.txt
```
